BEGIN;

CREATE SCHEMA IF NOT EXISTS iqbf;
SET LOCAL search_path TO iqbf, public, pg_catalog;

CREATE TABLE IF NOT EXISTS schema_migration (
    version       VARCHAR(40) PRIMARY KEY,
    descripcion   TEXT NOT NULL,
    aplicado_en   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Línea base autocontenida del núcleo operacional. No contiene inventario,
-- fotografías, censos ni credenciales: esos datos se cargan por procesos
-- controlados y separados de la creación del esquema.
CREATE TABLE IF NOT EXISTS carrera (
    id_carrera  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(120) NOT NULL UNIQUE,
    estado      VARCHAR(20) NOT NULL DEFAULT 'ACTIVO'
      CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS laboratorio (
    id_laboratorio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrera     INTEGER REFERENCES carrera(id_carrera) ON DELETE RESTRICT,
    nombre         VARCHAR(120) NOT NULL UNIQUE,
    estado         VARCHAR(20) NOT NULL DEFAULT 'ACTIVO'
      CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS proveedor (
    id_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(160) NOT NULL,
    ruc          VARCHAR(11) UNIQUE,
    estado       VARCHAR(20) NOT NULL DEFAULT 'ACTIVO'
      CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS procedencia (
    id_procedencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(120) NOT NULL,
    pais           VARCHAR(80)
);

-- INVESTIGADOR conserva el concepto ACTOR de Core V3 y admite tanto PERSONA
-- como AREA. Sprint 1 añade después sus identificadores y alcances.
CREATE TABLE IF NOT EXISTS investigador (
    id_investigador INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(120) NOT NULL UNIQUE,
    tipo            VARCHAR(10) NOT NULL DEFAULT 'PERSONA'
      CHECK (tipo IN ('PERSONA', 'AREA')),
    estado          VARCHAR(20) NOT NULL DEFAULT 'ACTIVO'
      CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(120) NOT NULL,
    email      VARCHAR(160) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    rol        VARCHAR(30) NOT NULL DEFAULT 'DOCIMASIA',
    estado     VARCHAR(20) NOT NULL DEFAULT 'ACTIVO'
      CHECK (estado IN ('ACTIVO', 'BLOQUEADO', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS insumo (
    id_insumo        VARCHAR(20) PRIMARY KEY,
    nombre_comercial VARCHAR(160) NOT NULL,
    tipo             VARCHAR(10) NOT NULL
      CHECK (tipo IN ('LIQUIDO', 'SOLIDO')),
    estado           VARCHAR(20) NOT NULL DEFAULT 'VIGENTE'
      CHECK (estado IN ('VIGENTE', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS presentacion (
    id_presentacion     VARCHAR(30) PRIMARY KEY,
    id_insumo           VARCHAR(20) NOT NULL
      REFERENCES insumo(id_insumo) ON DELETE RESTRICT,
    codigo_bf_sunat     VARCHAR(20),
    codigo_presentacion VARCHAR(20),
    concentracion       VARCHAR(40),
    capacidad           NUMERIC(12,4) NOT NULL CHECK (capacidad > 0),
    unidad              VARCHAR(4) NOT NULL
      CHECK (unidad IN ('mL', 'L', 'g', 'kg')),
    tipo_envase         VARCHAR(40),
    peso_neto_kg        NUMERIC(12,5)
      CHECK (peso_neto_kg IS NULL OR peso_neto_kg >= 0),
    densidad            NUMERIC(10,6)
      CHECK (densidad IS NULL OR densidad > 0),
    estado              VARCHAR(20) NOT NULL DEFAULT 'VIGENTE'
      CHECK (estado IN ('VIGENTE', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS lote (
    id_lote                    INTEGER GENERATED BY DEFAULT AS IDENTITY
      PRIMARY KEY,
    id_presentacion            VARCHAR(30) NOT NULL
      REFERENCES presentacion(id_presentacion) ON DELETE RESTRICT,
    id_proveedor               INTEGER
      REFERENCES proveedor(id_proveedor) ON DELETE RESTRICT,
    id_procedencia             INTEGER
      REFERENCES procedencia(id_procedencia) ON DELETE RESTRICT,
    id_laboratorio_solicitante INTEGER
      REFERENCES laboratorio(id_laboratorio) ON DELETE RESTRICT,
    grado_pureza               VARCHAR(40),
    numero_lote                VARCHAR(60),
    densidad                   NUMERIC(10,6)
      CHECK (densidad IS NULL OR densidad > 0),
    fecha_ingreso              DATE,
    fecha_caducidad            DATE,
    estado                     VARCHAR(20) NOT NULL DEFAULT 'ACTIVO'
      CHECK (estado IN ('ACTIVO', 'AGOTADO', 'DADO_DE_BAJA')),
    CONSTRAINT ck_lote_fechas_baseline
      CHECK (
        fecha_caducidad IS NULL
        OR fecha_ingreso IS NULL
        OR fecha_caducidad >= fecha_ingreso
      )
);

CREATE TABLE IF NOT EXISTS frasco (
    id_frasco             VARCHAR(40) PRIMARY KEY,
    id_lote               INTEGER NOT NULL
      REFERENCES lote(id_lote) ON DELETE RESTRICT,
    id_investigador       INTEGER
      REFERENCES investigador(id_investigador) ON DELETE RESTRICT,
    id_laboratorio_actual INTEGER
      REFERENCES laboratorio(id_laboratorio) ON DELETE RESTRICT,
    peso_bruto_g          NUMERIC(14,4)
      CHECK (peso_bruto_g IS NULL OR peso_bruto_g >= 0),
    tara_g                NUMERIC(14,4)
      CHECK (tara_g IS NULL OR tara_g >= 0),
    peso_neto_inicial_g   NUMERIC(14,4)
      CHECK (peso_neto_inicial_g IS NULL OR peso_neto_inicial_g >= 0),
    peso_neto_actual_g    NUMERIC(14,4) NOT NULL DEFAULT 0
      CHECK (peso_neto_actual_g >= 0),
    volumen_inicial_ml    NUMERIC(14,4)
      CHECK (volumen_inicial_ml IS NULL OR volumen_inicial_ml >= 0),
    estado                VARCHAR(20) NOT NULL DEFAULT 'EN_USO'
      CHECK (estado IN ('EN_USO', 'AGOTADO', 'DADO_DE_BAJA')),
    observaciones         TEXT,
    CONSTRAINT ck_frasco_bruto_tara_baseline
      CHECK (
        peso_bruto_g IS NULL
        OR tara_g IS NULL
        OR peso_bruto_g >= tara_g
      )
);

CREATE TABLE IF NOT EXISTS kardex (
    id_movimiento               INTEGER GENERATED BY DEFAULT AS IDENTITY
      PRIMARY KEY,
    id_frasco                   VARCHAR(40) NOT NULL
      REFERENCES frasco(id_frasco) ON DELETE RESTRICT,
    tipo_movimiento             VARCHAR(15) NOT NULL
      CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA', 'TRANSFERENCIA')),
    motivo                      VARCHAR(30) NOT NULL
      CHECK (
        motivo IN (
          'compra', 'entrega_directa', 'consumo_laboratorio',
          'transferencia', 'censo_inicial', 'ajuste_inventario',
          'correccion'
        )
      ),
    cantidad_g                  NUMERIC(14,4) NOT NULL
      CHECK (cantidad_g >= 0),
    id_laboratorio_origen       INTEGER
      REFERENCES laboratorio(id_laboratorio) ON DELETE RESTRICT,
    id_laboratorio_destino      INTEGER
      REFERENCES laboratorio(id_laboratorio) ON DELETE RESTRICT,
    id_investigador_destinatario INTEGER
      REFERENCES investigador(id_investigador) ON DELETE RESTRICT,
    densidad_aplicada           NUMERIC(10,6),
    fecha_hora                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    registrado_por              INTEGER NOT NULL
      REFERENCES usuario(id_usuario) ON DELETE RESTRICT,
    saldo_resultante_g          NUMERIC(14,4) NOT NULL,
    fecha_operacion             DATE NOT NULL DEFAULT CURRENT_DATE
      CHECK (fecha_operacion <= CURRENT_DATE),
    curso                       VARCHAR(160),
    usuario_final               VARCHAR(160),
    peso_antes_g                NUMERIC(14,4),
    peso_despues_g              NUMERIC(14,4),
    CONSTRAINT ck_kardex_transferencia_baseline
      CHECK (
        tipo_movimiento <> 'TRANSFERENCIA'
        OR (
          cantidad_g = 0
          AND (
            id_laboratorio_destino IS NOT NULL
            OR id_investigador_destinatario IS NOT NULL
          )
        )
      )
);

CREATE INDEX IF NOT EXISTS ix_kardex_frasco
    ON kardex (id_frasco, id_movimiento);

CREATE OR REPLACE FUNCTION fn_frasco_guardia()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path TO iqbf, pg_catalog, pg_temp
AS $$
BEGIN
  IF NEW.peso_neto_actual_g IS DISTINCT FROM OLD.peso_neto_actual_g
     AND COALESCE(current_setting('iqbf.mov', true), '0') <> '1' THEN
    RAISE EXCEPTION
      'El saldo del frasco % solo puede cambiar registrando un movimiento en kardex',
      NEW.id_frasco;
  END IF;
  RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION fn_kardex_antes()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path TO iqbf, pg_catalog, pg_temp
AS $$
DECLARE
  v_saldo     NUMERIC(14,4);
  v_capacidad NUMERIC(14,4);
  v_tipo      VARCHAR(10);
  v_signo     INTEGER;
BEGIN
  SELECT f.peso_neto_actual_g, f.peso_neto_inicial_g, i.tipo
    INTO v_saldo, v_capacidad, v_tipo
    FROM frasco f
    JOIN lote l         ON l.id_lote = f.id_lote
    JOIN presentacion p ON p.id_presentacion = l.id_presentacion
    JOIN insumo i       ON i.id_insumo = p.id_insumo
   WHERE f.id_frasco = NEW.id_frasco
   FOR UPDATE OF f;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'El frasco % no existe', NEW.id_frasco;
  END IF;

  IF NEW.densidad_aplicada IS NULL THEN
    SELECT COALESCE(l.densidad, p.densidad)
      INTO NEW.densidad_aplicada
      FROM frasco f
      JOIN lote l         ON l.id_lote = f.id_lote
      JOIN presentacion p ON p.id_presentacion = l.id_presentacion
     WHERE f.id_frasco = NEW.id_frasco;
  END IF;

  IF v_tipo = 'LIQUIDO' AND NEW.densidad_aplicada IS NULL THEN
    RAISE EXCEPTION 'Falta la densidad para el frasco % (liquido).', NEW.id_frasco;
  END IF;

  v_signo := CASE NEW.tipo_movimiento
               WHEN 'ENTRADA' THEN 1
               WHEN 'SALIDA' THEN -1
               ELSE 0
             END;

  IF v_signo = -1 AND NEW.cantidad_g > v_saldo THEN
    RAISE EXCEPTION
      'Saldo insuficiente en el frasco %: quedan % g y se intentan retirar % g',
      NEW.id_frasco, v_saldo, NEW.cantidad_g;
  END IF;

  NEW.saldo_resultante_g := v_saldo + (v_signo * NEW.cantidad_g);

  IF v_signo = 1
     AND v_capacidad IS NOT NULL
     AND NEW.saldo_resultante_g > v_capacidad THEN
    RAISE EXCEPTION
      'El frasco % no admite % g: quedaria con % g y su capacidad es % g',
      NEW.id_frasco, NEW.cantidad_g, NEW.saldo_resultante_g, v_capacidad;
  END IF;

  RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION fn_kardex_despues()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path TO iqbf, pg_catalog, pg_temp
AS $$
BEGIN
  PERFORM set_config('iqbf.mov', '1', true);
  UPDATE frasco
     SET peso_neto_actual_g = NEW.saldo_resultante_g,
         estado = CASE
           WHEN NEW.saldo_resultante_g = 0 AND estado = 'EN_USO'
             THEN 'AGOTADO'
           WHEN NEW.saldo_resultante_g > 0 AND estado = 'AGOTADO'
             THEN 'EN_USO'
           ELSE estado
         END,
         id_laboratorio_actual = CASE
           WHEN NEW.tipo_movimiento = 'TRANSFERENCIA'
                AND NEW.id_laboratorio_destino IS NOT NULL
             THEN NEW.id_laboratorio_destino
           ELSE id_laboratorio_actual
         END,
         id_investigador = CASE
           WHEN NEW.tipo_movimiento = 'TRANSFERENCIA'
                AND NEW.id_investigador_destinatario IS NOT NULL
             THEN NEW.id_investigador_destinatario
           ELSE id_investigador
         END
   WHERE id_frasco = NEW.id_frasco;
  PERFORM set_config('iqbf.mov', '0', true);
  RETURN NULL;
END
$$;

CREATE OR REPLACE FUNCTION fn_kardex_inmutable()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path TO iqbf, pg_catalog, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION
    'El kardex no se modifica ni se borra. Registre un movimiento de correccion.';
END
$$;

DROP TRIGGER IF EXISTS tg_frasco_guardia ON frasco;
CREATE TRIGGER tg_frasco_guardia
BEFORE UPDATE ON frasco
FOR EACH ROW EXECUTE FUNCTION fn_frasco_guardia();

DROP TRIGGER IF EXISTS tg_kardex_antes ON kardex;
CREATE TRIGGER tg_kardex_antes
BEFORE INSERT ON kardex
FOR EACH ROW EXECUTE FUNCTION fn_kardex_antes();

DROP TRIGGER IF EXISTS tg_kardex_despues ON kardex;
CREATE TRIGGER tg_kardex_despues
AFTER INSERT ON kardex
FOR EACH ROW EXECUTE FUNCTION fn_kardex_despues();

DROP TRIGGER IF EXISTS tg_kardex_inmutable ON kardex;
CREATE TRIGGER tg_kardex_inmutable
BEFORE UPDATE OR DELETE ON kardex
FOR EACH ROW EXECUTE FUNCTION fn_kardex_inmutable();

INSERT INTO schema_migration (version, descripcion)
VALUES ('000', 'Linea base autocontenida del nucleo operacional IQBF')
ON CONFLICT (version) DO NOTHING;

COMMIT;
