BEGIN;

CREATE SCHEMA IF NOT EXISTS iqbf;
SET LOCAL search_path TO iqbf, public, pg_catalog;

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS schema_migration (
    version       VARCHAR(40) PRIMARY KEY,
    descripcion   TEXT NOT NULL,
    aplicado_en   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION normalizar_busqueda(valor TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
    SELECT lower(
      public.unaccent('public.unaccent'::regdictionary, coalesce(valor, ''))
    )
$$;

-- Organización: se preservan CARRERA y LABORATORIO y se añaden únicamente las
-- entidades que el Sprint 1 exige y que no existían en el MVP.
CREATE TABLE IF NOT EXISTS establecimiento (
    id_establecimiento  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(30) NOT NULL UNIQUE,
    nombre              VARCHAR(160) NOT NULL,
    estado              VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    vigencia_desde      DATE NOT NULL DEFAULT CURRENT_DATE,
    vigencia_hasta      DATE,
    CONSTRAINT ck_establecimiento_estado
      CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT ck_establecimiento_vigencia
      CHECK (vigencia_hasta IS NULL OR vigencia_hasta >= vigencia_desde)
);

ALTER TABLE carrera
    ADD COLUMN IF NOT EXISTS codigo VARCHAR(30),
    ADD COLUMN IF NOT EXISTS vigencia_desde DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS vigencia_hasta DATE;

UPDATE carrera
   SET codigo = concat('CAR-', lpad(id_carrera::text, 4, '0'))
 WHERE codigo IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_carrera_codigo_normalizado
    ON carrera (normalizar_busqueda(codigo));

ALTER TABLE laboratorio
    ADD COLUMN IF NOT EXISTS codigo VARCHAR(30),
    ADD COLUMN IF NOT EXISTS id_establecimiento INTEGER
      REFERENCES establecimiento(id_establecimiento),
    ADD COLUMN IF NOT EXISTS vigencia_desde DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS vigencia_hasta DATE;

UPDATE laboratorio
   SET codigo = concat('LAB-', lpad(id_laboratorio::text, 4, '0'))
 WHERE codigo IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_laboratorio_codigo_normalizado
    ON laboratorio (normalizar_busqueda(codigo));

CREATE TABLE IF NOT EXISTS ubicacion (
    id_ubicacion        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(30) NOT NULL UNIQUE,
    nombre              VARCHAR(160) NOT NULL,
    id_establecimiento  INTEGER NOT NULL
      REFERENCES establecimiento(id_establecimiento),
    id_laboratorio      INTEGER REFERENCES laboratorio(id_laboratorio),
    estado              VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    vigencia_desde      DATE NOT NULL DEFAULT CURRENT_DATE,
    vigencia_hasta      DATE,
    CONSTRAINT ck_ubicacion_estado CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT ck_ubicacion_vigencia
      CHECK (vigencia_hasta IS NULL OR vigencia_hasta >= vigencia_desde)
);

INSERT INTO establecimiento (codigo, nombre)
VALUES ('ULIMA', 'Universidad de Lima')
ON CONFLICT (codigo) DO NOTHING;

UPDATE laboratorio
   SET id_establecimiento = (
       SELECT id_establecimiento
         FROM establecimiento
        WHERE codigo = 'ULIMA'
   )
 WHERE id_establecimiento IS NULL;

-- Personas y cuentas.
ALTER TABLE investigador
    ADD COLUMN IF NOT EXISTS codigo_institucional VARCHAR(40),
    ADD COLUMN IF NOT EXISTS email VARCHAR(160),
    ADD COLUMN IF NOT EXISTS id_carrera INTEGER REFERENCES carrera(id_carrera),
    ADD COLUMN IF NOT EXISTS id_laboratorio INTEGER REFERENCES laboratorio(id_laboratorio),
    ADD COLUMN IF NOT EXISTS vigencia_desde DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS vigencia_hasta DATE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_investigador_codigo_institucional
    ON investigador (normalizar_busqueda(codigo_institucional))
    WHERE codigo_institucional IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_investigador_email
    ON investigador (normalizar_busqueda(email))
    WHERE email IS NOT NULL;

ALTER TABLE usuario
    ADD COLUMN IF NOT EXISTS codigo_institucional VARCHAR(40),
    ADD COLUMN IF NOT EXISTS alcance_global BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS intentos_fallidos INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bloqueado_hasta TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS ultimo_acceso TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_codigo_institucional
    ON usuario (normalizar_busqueda(codigo_institucional))
    WHERE codigo_institucional IS NOT NULL;

CREATE TABLE IF NOT EXISTS rol (
    codigo       VARCHAR(30) PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL,
    descripcion  TEXT NOT NULL,
    estado       VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT ck_rol_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

INSERT INTO rol (codigo, nombre, descripcion) VALUES
('RESPONSABLE_IQBF', 'Responsable IQBF', 'Administra reglas, maestros, cierres y reportes.'),
('OPERADOR_DOCIMASIA', 'Operador de Docimasia', 'Registra y consulta la operación diaria.'),
('DOCENTE_INVESTIGADOR', 'Docente o investigador', 'Consulta su alcance y atiende sustentos.'),
('APROBADOR', 'Aprobador', 'Resuelve excepciones y aprobaciones asignadas.'),
('AUDITOR', 'Auditor', 'Consulta en modo de solo lectura.'),
('ADMIN_TECNICO', 'Administrador técnico', 'Administra cuentas y configuración técnica.')
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion;

CREATE TABLE IF NOT EXISTS usuario_rol (
    id_usuario  INTEGER NOT NULL REFERENCES usuario(id_usuario) ON DELETE RESTRICT,
    codigo_rol  VARCHAR(30) NOT NULL REFERENCES rol(codigo) ON DELETE RESTRICT,
    asignado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    asignado_por INTEGER REFERENCES usuario(id_usuario) ON DELETE RESTRICT,
    PRIMARY KEY (id_usuario, codigo_rol)
);

INSERT INTO usuario_rol (id_usuario, codigo_rol)
SELECT id_usuario,
       CASE rol
         WHEN 'DOCIMASIA' THEN 'OPERADOR_DOCIMASIA'
         WHEN 'ADMIN' THEN 'ADMIN_TECNICO'
         ELSE 'AUDITOR'
       END
  FROM usuario u
 WHERE NOT EXISTS (
       SELECT 1
         FROM usuario_rol ur
        WHERE ur.id_usuario = u.id_usuario
 )
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS usuario_alcance (
    id_usuario          INTEGER NOT NULL REFERENCES usuario(id_usuario) ON DELETE RESTRICT,
    id_establecimiento  INTEGER REFERENCES establecimiento(id_establecimiento) ON DELETE RESTRICT,
    id_laboratorio      INTEGER REFERENCES laboratorio(id_laboratorio) ON DELETE RESTRICT,
    asignado_en         TIMESTAMPTZ NOT NULL DEFAULT now(),
    asignado_por        INTEGER REFERENCES usuario(id_usuario) ON DELETE RESTRICT,
    CONSTRAINT ck_usuario_alcance_objeto
      CHECK (id_establecimiento IS NOT NULL OR id_laboratorio IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_alcance_establecimiento
    ON usuario_alcance (id_usuario, id_establecimiento)
    WHERE id_establecimiento IS NOT NULL AND id_laboratorio IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_alcance_laboratorio
    ON usuario_alcance (id_usuario, id_laboratorio)
    WHERE id_laboratorio IS NOT NULL;

CREATE TABLE IF NOT EXISTS sesion (
    id_sesion       UUID PRIMARY KEY,
    id_usuario      INTEGER NOT NULL REFERENCES usuario(id_usuario) ON DELETE RESTRICT,
    iniciada_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    expira_en       TIMESTAMPTZ NOT NULL,
    cerrada_en      TIMESTAMPTZ,
    revocada_en     TIMESTAMPTZ,
    ip_origen       INET,
    agente_usuario  TEXT,
    CONSTRAINT ck_sesion_expiracion CHECK (expira_en > iniciada_en)
);
CREATE INDEX IF NOT EXISTS ix_sesion_usuario_activa
    ON sesion (id_usuario, expira_en)
    WHERE revocada_en IS NULL AND cerrada_en IS NULL;

-- Maestros de insumo, presentación y densidad versionada.
ALTER TABLE insumo
    ADD COLUMN IF NOT EXISTS unidad_base VARCHAR(4) NOT NULL DEFAULT 'g',
    ADD COLUMN IF NOT EXISTS creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS uq_insumo_id_normalizado
    ON insumo (normalizar_busqueda(id_insumo));
CREATE INDEX IF NOT EXISTS ix_insumo_busqueda
    ON insumo (normalizar_busqueda(nombre_comercial));

ALTER TABLE presentacion
    ADD COLUMN IF NOT EXISTS equivalencia_g NUMERIC(14,4),
    ADD COLUMN IF NOT EXISTS vigencia_desde DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS vigencia_hasta DATE,
    ADD COLUMN IF NOT EXISTS creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now();

UPDATE presentacion
   SET equivalencia_g = peso_neto_kg * 1000
 WHERE equivalencia_g IS NULL
   AND peso_neto_kg IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_presentacion_id_normalizado
    ON presentacion (normalizar_busqueda(id_presentacion));
CREATE UNIQUE INDEX IF NOT EXISTS uq_presentacion_codigo_normalizado
    ON presentacion (normalizar_busqueda(codigo_presentacion))
    WHERE codigo_presentacion IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_presentacion_insumo_estado
    ON presentacion (id_insumo, estado);

CREATE TABLE IF NOT EXISTS densidad_vigencia (
    id_densidad       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_presentacion   VARCHAR(30) NOT NULL
      REFERENCES presentacion(id_presentacion) ON DELETE RESTRICT,
    valor             NUMERIC(10,6) NOT NULL CHECK (valor > 0),
    unidad            VARCHAR(12) NOT NULL DEFAULT 'g/mL',
    fuente            TEXT NOT NULL,
    vigencia_desde    DATE NOT NULL,
    vigencia_hasta    DATE,
    creado_por        INTEGER REFERENCES usuario(id_usuario) ON DELETE RESTRICT,
    creado_en         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_densidad_vigencia
      CHECK (vigencia_hasta IS NULL OR vigencia_hasta >= vigencia_desde)
);

CREATE OR REPLACE FUNCTION fn_densidad_no_solapada()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path TO iqbf, pg_catalog, pg_temp
AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext(NEW.id_presentacion));
  IF EXISTS (
      SELECT 1
        FROM densidad_vigencia d
       WHERE d.id_presentacion = NEW.id_presentacion
         AND d.id_densidad <> COALESCE(NEW.id_densidad, -1)
         AND daterange(d.vigencia_desde, COALESCE(d.vigencia_hasta, 'infinity'::date), '[]')
             && daterange(NEW.vigencia_desde, COALESCE(NEW.vigencia_hasta, 'infinity'::date), '[]')
  ) THEN
    RAISE EXCEPTION 'La presentacion % ya tiene una densidad vigente en ese periodo',
                    NEW.id_presentacion;
  END IF;
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS tg_densidad_no_solapada ON densidad_vigencia;
CREATE TRIGGER tg_densidad_no_solapada
BEFORE INSERT OR UPDATE ON densidad_vigencia
FOR EACH ROW EXECUTE FUNCTION fn_densidad_no_solapada();

INSERT INTO densidad_vigencia
    (id_presentacion, valor, fuente, vigencia_desde)
SELECT id_presentacion, densidad, 'MIGRACION_PRESENTACION', DATE '1900-01-01'
  FROM presentacion p
 WHERE densidad IS NOT NULL
   AND NOT EXISTS (
       SELECT 1
         FROM densidad_vigencia d
        WHERE d.id_presentacion = p.id_presentacion
   );

-- Bitácora transversal. El backend fija iqbf.actor_id e iqbf.request_id dentro
-- de cada transacción; los cambios directos siguen quedando registrados.
CREATE TABLE IF NOT EXISTS bitacora (
    id_evento      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora     TIMESTAMPTZ NOT NULL DEFAULT now(),
    id_usuario     INTEGER REFERENCES usuario(id_usuario) ON DELETE RESTRICT,
    accion         VARCHAR(12) NOT NULL,
    entidad        VARCHAR(80) NOT NULL,
    entidad_id     TEXT,
    valores_antes  JSONB,
    valores_despues JSONB,
    request_id     UUID,
    origen         VARCHAR(20) NOT NULL DEFAULT 'BD'
);
CREATE INDEX IF NOT EXISTS ix_bitacora_entidad
    ON bitacora (entidad, entidad_id, fecha_hora DESC);
CREATE INDEX IF NOT EXISTS ix_bitacora_usuario
    ON bitacora (id_usuario, fecha_hora DESC);

CREATE OR REPLACE FUNCTION fn_auditar_sprint1()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO iqbf, pg_catalog, pg_temp
AS $$
DECLARE
  v_actor_text TEXT := current_setting('iqbf.actor_id', true);
  v_request_text TEXT := current_setting('iqbf.request_id', true);
  v_old JSONB;
  v_new JSONB;
  v_id TEXT;
BEGIN
  -- Nunca copie credenciales (ni siquiera hashes) a la bitácora.
  v_old := CASE
    WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) - 'contrasena'
  END;
  v_new := CASE
    WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) - 'contrasena'
  END;
  v_id := COALESCE(
      v_new ->> ('id_' || TG_TABLE_NAME),
      v_old ->> ('id_' || TG_TABLE_NAME),
      v_new ->> 'codigo',
      v_old ->> 'codigo',
      v_new ->> 'id_presentacion',
      v_old ->> 'id_presentacion',
      v_new ->> 'id_insumo',
      v_old ->> 'id_insumo',
      v_new ->> 'id_usuario',
      v_old ->> 'id_usuario'
  );

  INSERT INTO bitacora (
      id_usuario, accion, entidad, entidad_id,
      valores_antes, valores_despues, request_id, origen
  ) VALUES (
      CASE WHEN v_actor_text ~ '^[0-9]+$' THEN v_actor_text::integer END,
      TG_OP, TG_TABLE_NAME, v_id, v_old, v_new,
      CASE
        WHEN v_request_text ~
          '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        THEN v_request_text::uuid
      END,
      CASE WHEN v_actor_text ~ '^[0-9]+$' THEN 'API' ELSE 'BD' END
  );

  RETURN COALESCE(NEW, OLD);
END
$$;

DO $$
DECLARE
  v_tabla TEXT;
BEGIN
  FOREACH v_tabla IN ARRAY ARRAY[
      'usuario', 'usuario_rol', 'usuario_alcance',
      'establecimiento', 'carrera', 'laboratorio', 'ubicacion',
      'investigador', 'insumo', 'presentacion', 'densidad_vigencia'
  ]
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS tg_aud_%I ON %I', v_tabla, v_tabla);
    EXECUTE format(
      'CREATE TRIGGER tg_aud_%I AFTER INSERT OR UPDATE OR DELETE ON %I '
      'FOR EACH ROW EXECUTE FUNCTION fn_auditar_sprint1()',
      v_tabla, v_tabla
    );
  END LOOP;
END
$$;

INSERT INTO schema_migration (version, descripcion)
VALUES ('001', 'Nucleo de identidad, organizacion, maestros y auditoria del Sprint 1')
ON CONFLICT (version) DO NOTHING;

COMMIT;
