BEGIN;

SET LOCAL search_path TO iqbf, public, pg_catalog;

-- ═══════════════════════════════════════════════════════════════════════════
-- 005 · Búsqueda por nombre común y por laboratorio (US-10, US-11)
--
-- El caso que la motiva es literal: un profesor entra y pide «etanol del
-- laboratorio de alimentos». Hoy eso no se puede responder por dos motivos.
--
-- 1. En el censo, el etanol está escrito de SEIS formas distintas —
--    «Ethanol», «Etanol absoluto», «Alcohol Etílico Absoluto», «Ethanol
--    absolute for analysis / Etanol / Etanolo»…—. Quien busca «etanol»
--    encuentra unos pocos y cree que son todos. Por eso INSUMO_ALIAS.
--
-- 2. El laboratorio no era una dimensión consultable: el dato existía en el
--    rótulo del frasco pero no en ninguna columna con la que se pueda filtrar.
-- ═══════════════════════════════════════════════════════════════════════════


-- ─── 1 · Alias de búsqueda ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS insumo_alias (
    id_alias   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_insumo  VARCHAR(20) NOT NULL
                 REFERENCES insumo(id_insumo) ON DELETE CASCADE,
    alias      VARCHAR(160) NOT NULL,
    origen     VARCHAR(40) NOT NULL DEFAULT 'catalogo',
    creado_en  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_insumo_alias
    ON insumo_alias (id_insumo, normalizar_busqueda(alias));
CREATE INDEX IF NOT EXISTS ix_insumo_alias_busqueda
    ON insumo_alias (normalizar_busqueda(alias));

COMMENT ON TABLE insumo_alias IS
  'Nombres alternativos con los que el laboratorio pide una sustancia. Sin '
  'esto, «etanol» no encuentra los frascos rotulados «Ethanol».';


-- Un alias por cada forma en que el censo escribe la sustancia. Se añaden en
-- cuanto exista el insumo: los que aún no están cargados no rompen nada.
INSERT INTO insumo_alias (id_insumo, alias, origen)
SELECT v.id_insumo, v.alias, 'censo'
  FROM (VALUES
    ('IQF0102', 'HCl'),
    ('IQF0102', 'Acido Clorhidrico'),
    ('IQF0102', 'Ácido muriático'),
    ('IQF0102', 'Acido Clorhidrico Ultrex'),
    ('IQF0102', 'Clorhídrico'),
    ('IQF0106', 'HNO3'),
    ('IQF0106', 'Acido Nitrico'),
    ('IQF0106', 'Nítrico'),
    ('IQF0108', 'H2SO4'),
    ('IQF0108', 'Acido Sulfurico'),
    ('IQF0108', 'Sulfúrico'),
    ('IQF0304', 'Etanol'),
    ('IQF0304', 'Ethanol'),
    ('IQF0304', 'Etanol absoluto'),
    ('IQF0304', 'Alcohol etílico'),
    ('IQF0304', 'Alcohol Etílico Absoluto'),
    ('IQF0304', 'Ethanol absolute'),
    ('IQF0304', 'Etanolo'),
    ('IQF0304', 'Alcohol'),
    ('IQF0308', 'Metanol'),
    ('IQF0308', 'Methanol'),
    ('IQF0308', 'Alcohol metílico'),
    ('IQF0401', 'Acetona'),
    ('IQF0401', 'Propanona'),
    ('IQF0401', 'Acetona p.a.'),
    ('IQF0501', 'Éter'),
    ('IQF0501', 'Eter etilico'),
    ('IQF0501', 'Éter dietílico'),
    ('IQF0501', 'Éter sulfúrico'),
    ('IQF0501', 'Dietil eter'),
    ('IQF0605', 'Hexano'),
    ('IQF0605', 'N-Hexano'),
    ('IQF0613', 'Tolueno'),
    ('IQF0613', 'Toluene'),
    ('IQF0702', 'Amoniaco'),
    ('IQF0702', 'Hidroxido de amonio'),
    ('IQF0702', 'Amoníaco acuoso'),
    ('IQF0708', 'Soda caustica'),
    ('IQF0708', 'NaOH'),
    ('IQF0708', 'Hidroxido de sodio'),
    ('IQF0708', 'Sosa')
  ) AS v(id_insumo, alias)
  JOIN insumo i ON i.id_insumo = v.id_insumo
 WHERE NOT EXISTS (
   SELECT 1 FROM insumo_alias a
    WHERE a.id_insumo = v.id_insumo
      AND normalizar_busqueda(a.alias) = normalizar_busqueda(v.alias)
 );


-- ─── 2 · Los laboratorios que el censo nombra ──────────────────────────────
-- Se crean con el nombre del rótulo. No se inventa ninguno: si un frasco no
-- dice de qué laboratorio es, se queda sin laboratorio y sale en la lista de
-- «sin asignar», que es una pregunta abierta y no un dato falso.

INSERT INTO laboratorio (nombre, codigo)
SELECT v.nombre, v.codigo
  FROM (VALUES
    ('Docimasia',                 'LAB-DOCIMASIA'),
    ('Ingeniería Civil',          'LAB-ING-CIVIL'),
    ('Laboratorio de Alimentos',  'LAB-ALIMENTOS'),
    ('Laboratorio de Química',    'LAB-QUIMICA'),
    ('FAUGRO Microbiología',      'LAB-FAUGRO'),
    ('Académico',                 'LAB-ACADEMICO')
  ) AS v(nombre, codigo)
 WHERE NOT EXISTS (
   SELECT 1 FROM laboratorio l WHERE l.nombre = v.nombre
 );


-- ─── 3 · La búsqueda unificada ─────────────────────────────────────────────
-- Una sola función para que el buscador de la API y cualquier consulta suelta
-- respondan lo mismo. Cubre: nombre del insumo, sus alias, código interno del
-- frasco, código SUNAT, código de presentación y número de lote.

CREATE OR REPLACE FUNCTION fn_frasco_coincide(
    p_id_frasco       VARCHAR,
    p_id_insumo       VARCHAR,
    p_nombre          VARCHAR,
    p_codigo_sunat    VARCHAR,
    p_id_presentacion VARCHAR,
    p_numero_lote     VARCHAR,
    p_texto           TEXT
) RETURNS BOOLEAN
LANGUAGE sql STABLE AS $$
  SELECT p_texto IS NULL
      OR normalizar_busqueda(p_id_frasco)             LIKE '%' || normalizar_busqueda(p_texto) || '%'
      OR normalizar_busqueda(p_nombre)                LIKE '%' || normalizar_busqueda(p_texto) || '%'
      OR normalizar_busqueda(COALESCE(p_codigo_sunat, ''))    LIKE '%' || normalizar_busqueda(p_texto) || '%'
      OR normalizar_busqueda(COALESCE(p_id_presentacion, '')) LIKE '%' || normalizar_busqueda(p_texto) || '%'
      OR normalizar_busqueda(COALESCE(p_numero_lote, ''))     LIKE '%' || normalizar_busqueda(p_texto) || '%'
      OR EXISTS (
           SELECT 1 FROM insumo_alias a
            WHERE a.id_insumo = p_id_insumo
              AND normalizar_busqueda(a.alias) LIKE '%' || normalizar_busqueda(p_texto) || '%'
         );
$$;


-- ─── 4 · El laboratorio entra en la vista de inventario ────────────────────

DROP VIEW IF EXISTS v_alertas_v4 CASCADE;
DROP VIEW IF EXISTS v_declaracion_sunat CASCADE;
DROP VIEW IF EXISTS v_saldo_investigador_v4 CASCADE;
DROP VIEW IF EXISTS v_inventario_v4 CASCADE;

CREATE VIEW v_inventario_v4 AS
SELECT
    f.id_frasco, i.id_insumo, i.nombre_comercial, i.tipo,
    p.id_presentacion, p.codigo_bf_sunat, p.concentracion, p.capacidad,
    p.unidad, p.tipo_envase, p.equivalencia_g AS contenido_nominal_g,
    l.id_lote, l.numero_lote, l.grado_pureza, l.fecha_ingreso, l.fecha_caducidad,
    f.peso_bruto_g, f.tara_g, f.peso_neto_inicial_g, f.peso_neto_actual_g,
    f.saldo_indeterminado, f.fuente_tara, f.fecha_pesaje, f.condicion_envase,
    f.estado AS estado_frasco, f.observaciones,
    inv.id_investigador, inv.nombre AS custodio,
    lab.id_laboratorio, lab.nombre AS laboratorio,
    u.id_ubicacion, u.nombre AS ubicacion, u.casillero, u.nombre_puerta,
    u.nivel, u.posicion, f.precision_ubicacion,
    COALESCE(l.densidad, p.densidad) AS densidad_aplicable,
    CASE
      WHEN i.tipo = 'LIQUIDO' AND COALESCE(l.densidad, p.densidad) IS NOT NULL
       AND f.peso_neto_actual_g IS NOT NULL
      THEN round(f.peso_neto_actual_g / COALESCE(l.densidad, p.densidad), 4)
    END AS volumen_actual_ml,
    CASE
      WHEN p.equivalencia_g IS NULL OR p.equivalencia_g = 0 THEN NULL
      WHEN f.peso_neto_actual_g IS NULL THEN NULL
      ELSE round(f.peso_neto_actual_g / p.equivalencia_g, 4)
    END AS fraccion_llenado,
    CASE
      WHEN l.fecha_caducidad IS NULL             THEN 'POR_CONFIRMAR'
      WHEN l.fecha_caducidad < CURRENT_DATE      THEN 'VENCIDO'
      WHEN l.fecha_caducidad < CURRENT_DATE + 90 THEN 'POR_VENCER'
      ELSE 'VIGENTE'
    END AS estado_caducidad,
    mov.ultimo_movimiento,
    CASE WHEN mov.ultimo_movimiento IS NULL THEN NULL
         ELSE (CURRENT_DATE - mov.ultimo_movimiento::date) END AS dias_sin_movimiento
  FROM frasco f
  JOIN lote l                ON l.id_lote = f.id_lote
  JOIN presentacion p        ON p.id_presentacion = l.id_presentacion
  JOIN insumo i              ON i.id_insumo = p.id_insumo
  LEFT JOIN investigador inv ON inv.id_investigador = f.id_investigador
  LEFT JOIN ubicacion u      ON u.id_ubicacion = f.id_ubicacion
  -- El laboratorio del frasco manda; si no lo tiene, se hereda del custodio.
  LEFT JOIN laboratorio lab
         ON lab.id_laboratorio = COALESCE(f.id_laboratorio_actual, inv.id_laboratorio)
  LEFT JOIN LATERAL (
        SELECT max(k.fecha_hora) AS ultimo_movimiento
          FROM kardex k WHERE k.id_frasco = f.id_frasco
  ) mov ON TRUE;

CREATE VIEW v_alertas_v4 AS
SELECT v.*,
       CASE
         WHEN v.saldo_indeterminado              THEN '0-SALDO_INDETERMINADO'
         WHEN v.estado_caducidad = 'VENCIDO'     THEN '1-VENCIDO'
         WHEN v.tipo = 'LIQUIDO'
          AND v.densidad_aplicable IS NULL       THEN '2-DENSIDAD_PENDIENTE'
         WHEN v.codigo_bf_sunat IS NULL          THEN '3-SIN_CODIGO_SUNAT'
         WHEN v.id_investigador IS NULL          THEN '4-SIN_CUSTODIO'
         WHEN v.estado_caducidad = 'POR_VENCER'  THEN '5-POR_VENCER'
         WHEN v.dias_sin_movimiento >= 730       THEN '6-DORMIDO'
         WHEN v.peso_neto_actual_g = 0
          AND v.estado_frasco <> 'AGOTADO'       THEN '7-REVISAR_ESTADO'
         ELSE '8-SIN_ALERTA'
       END AS alerta_prioritaria
  FROM v_inventario_v4 v;

CREATE VIEW v_declaracion_sunat AS
SELECT v.codigo_bf_sunat, v.id_insumo,
       max(v.nombre_comercial) AS nombre_comercial,
       max(v.tipo)             AS tipo,
       count(*)                AS frascos,
       count(*) FILTER (WHERE v.saldo_indeterminado) AS frascos_indeterminados,
       round(sum(v.peso_neto_actual_g) / 1000.0, 4)  AS saldo_kg,
       round(sum(v.peso_neto_actual_g)
               FILTER (WHERE v.estado_caducidad = 'VENCIDO') / 1000.0, 4)
                                                     AS saldo_vencido_kg
  FROM v_inventario_v4 v
 WHERE v.estado_frasco <> 'DADO_DE_BAJA'
   AND v.codigo_bf_sunat IS NOT NULL
 GROUP BY v.codigo_bf_sunat, v.id_insumo;

CREATE VIEW v_saldo_investigador_v4 AS
SELECT inv.id_investigador, inv.nombre AS custodio,
       count(v.id_frasco)                                     AS frascos,
       count(*) FILTER (WHERE v.estado_caducidad = 'VENCIDO')  AS frascos_vencidos,
       count(*) FILTER (WHERE v.saldo_indeterminado)           AS frascos_indeterminados,
       round(COALESCE(sum(v.peso_neto_actual_g), 0) / 1000.0, 4) AS saldo_kg
  FROM investigador inv
  LEFT JOIN v_inventario_v4 v
         ON v.id_investigador = inv.id_investigador
        AND v.estado_frasco <> 'DADO_DE_BAJA'
 GROUP BY inv.id_investigador, inv.nombre;

-- US-11 · el stock visto por laboratorio, que es como lo pide un profesor.
CREATE VIEW v_saldo_laboratorio AS
SELECT COALESCE(v.id_laboratorio, -1)              AS id_laboratorio,
       COALESCE(v.laboratorio, 'SIN ASIGNAR')      AS laboratorio,
       v.id_insumo,
       v.nombre_comercial,
       count(*)                                    AS frascos,
       count(*) FILTER (WHERE v.estado_caducidad = 'VENCIDO') AS frascos_vencidos,
       round(sum(v.peso_neto_actual_g) / 1000.0, 4) AS saldo_kg
  FROM v_inventario_v4 v
 WHERE v.estado_frasco <> 'DADO_DE_BAJA'
 GROUP BY 1, 2, v.id_insumo, v.nombre_comercial;

CREATE INDEX IF NOT EXISTS ix_frasco_laboratorio
    ON frasco (id_laboratorio_actual);

INSERT INTO schema_migration (version, descripcion)
VALUES ('005', 'Alias de busqueda por nombre comun y dimension laboratorio')
ON CONFLICT (version) DO NOTHING;

COMMIT;
