BEGIN;

SET LOCAL search_path TO iqbf, public, pg_catalog;

-- ═══════════════════════════════════════════════════════════════════════════
-- 010 · Épica E4 — Autorizaciones de uso y excepciones
--   US-023 registrar una autorización por titular, insumo y presentación
--   US-024 adjuntar el documento soporte, versionado
--   US-025 calcular el saldo autorizado en la unidad canónica
--   US-026 consultar autorizaciones y saldos vigentes
--   US-027 validar autorización y saldo antes de un consumo
--   US-028 solicitar una excepción cuando la regla lo permita
--   US-029 aprobar o rechazar excepciones de forma trazable
--
-- La unidad canónica es el GRAMO, igual que en el kardex. Lo que el
-- responsable teclea se conserva aparte (cantidad_registrada + unidad) para
-- poder enseñarle su propio número, pero todo lo que se compara está en
-- gramos: comparar litros con kilos es como se pierde una declaración.
-- ═══════════════════════════════════════════════════════════════════════════


-- ─── US-023 · La autorización ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS autorizacion (
    id_autorizacion    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    --: Folio legible. Es el número que se cita en un oficio.
    codigo             VARCHAR(30) NOT NULL UNIQUE,
    id_investigador    INTEGER NOT NULL REFERENCES investigador(id_investigador)
                         ON DELETE RESTRICT,
    id_insumo          VARCHAR(20) NOT NULL REFERENCES insumo(id_insumo)
                         ON DELETE RESTRICT,
    --: NULL = vale para cualquier presentación del insumo.
    id_presentacion    VARCHAR(30) REFERENCES presentacion(id_presentacion)
                         ON DELETE RESTRICT,
    id_establecimiento INTEGER NOT NULL REFERENCES establecimiento(id_establecimiento)
                         ON DELETE RESTRICT,
    id_laboratorio     INTEGER REFERENCES laboratorio(id_laboratorio)
                         ON DELETE RESTRICT,

    cantidad_autorizada_g NUMERIC(14,4) NOT NULL
                            CHECK (cantidad_autorizada_g > 0),
    --: Lo que tecleó el responsable, para poder devolvérselo tal cual.
    cantidad_registrada   NUMERIC(14,4),
    unidad_registrada     VARCHAR(4)
                            CHECK (unidad_registrada IS NULL
                                   OR unidad_registrada IN ('g','kg','mL','L')),
    densidad_aplicada     NUMERIC(10,6),

    vigencia_desde     DATE NOT NULL DEFAULT CURRENT_DATE,
    vigencia_hasta     DATE,

    --: BORRADOR se puede editar; VIGENTE ya no. REVOCADA la deja sin efecto
    --: sin borrarla. «Agotada» y «por vencer» NO son estados: se calculan,
    --: porque dependen del consumo y del reloj y guardarlos los deja rancios.
    estado             VARCHAR(20) NOT NULL DEFAULT 'BORRADOR'
                         CHECK (estado IN ('BORRADOR','VIGENTE','REVOCADA')),
    motivo_revocacion  TEXT,
    observaciones      TEXT,

    creado_por         INTEGER REFERENCES usuario(id_usuario),
    creado_en          TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_autorizacion_vigencia
      CHECK (vigencia_hasta IS NULL OR vigencia_hasta >= vigencia_desde),
    CONSTRAINT ck_autorizacion_revocada
      CHECK (estado <> 'REVOCADA' OR motivo_revocacion IS NOT NULL)
);

COMMENT ON TABLE autorizacion IS
  'US-023. Cuánto puede consumir un titular de un insumo, en qué plazo y con '
  'qué documento detrás. La cantidad se guarda en gramos: es la unidad en la '
  'que se compara contra el kardex.';

CREATE INDEX IF NOT EXISTS ix_autorizacion_titular
  ON autorizacion (id_investigador, id_insumo, estado);


-- La presentación tiene que ser del insumo autorizado. Sin esto se puede
-- autorizar «acetona» y colgarle una presentación de ácido nítrico.
CREATE OR REPLACE FUNCTION fn_autorizacion_coherente() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_insumo_de_pres VARCHAR(20);
BEGIN
  IF NEW.id_presentacion IS NOT NULL THEN
    SELECT id_insumo INTO v_insumo_de_pres
      FROM presentacion WHERE id_presentacion = NEW.id_presentacion;
    IF v_insumo_de_pres IS DISTINCT FROM NEW.id_insumo THEN
      RAISE EXCEPTION
        'La presentacion % no pertenece al insumo %',
        NEW.id_presentacion, NEW.id_insumo
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  -- Una autorización VIGENTE ya no se edita en su cantidad ni en su titular:
  -- para eso está la ampliación (otra autorización) o la revocación.
  IF TG_OP = 'UPDATE' AND OLD.estado = 'VIGENTE'
     AND NEW.estado = 'VIGENTE'
     AND (NEW.cantidad_autorizada_g IS DISTINCT FROM OLD.cantidad_autorizada_g
          OR NEW.id_investigador IS DISTINCT FROM OLD.id_investigador
          OR NEW.id_insumo IS DISTINCT FROM OLD.id_insumo) THEN
    RAISE EXCEPTION
      'Una autorizacion vigente no cambia de titular ni de cantidad: registre '
      'una ampliacion o revoquela'
      USING ERRCODE = 'check_violation';
  END IF;

  NEW.actualizado_en := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_autorizacion_coherente ON autorizacion;
CREATE TRIGGER tg_autorizacion_coherente
BEFORE INSERT OR UPDATE ON autorizacion
FOR EACH ROW EXECUTE FUNCTION fn_autorizacion_coherente();


-- ─── US-024 · El documento soporte, versionado ─────────────────────────────
-- Reemplazar un archivo NO borra el anterior: se añade una versión. En un
-- sistema fiscalizado, el documento que sustentaba una autorización el año
-- pasado tiene que seguir recuperable aunque hoy haya otro.

CREATE TABLE IF NOT EXISTS autorizacion_documento (
    id_documento    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_autorizacion INTEGER NOT NULL REFERENCES autorizacion(id_autorizacion)
                      ON DELETE RESTRICT,
    version         INTEGER NOT NULL,
    nombre_archivo  VARCHAR(200) NOT NULL,
    tipo_mime       VARCHAR(100) NOT NULL,
    tamano_bytes    INTEGER NOT NULL CHECK (tamano_bytes > 0),
    sha256          CHAR(64) NOT NULL,
    --: El binario vive aquí a propósito. Un oficio son unos cientos de kB y
    --: meter un almacén de objetos para eso añade un sitio más donde el
    --: respaldo puede quedar desincronizado del dato que lo justifica.
    contenido       BYTEA NOT NULL,
    subido_por      INTEGER REFERENCES usuario(id_usuario),
    subido_en       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id_autorizacion, version)
);

COMMENT ON TABLE autorizacion_documento IS
  'US-024. Soporte documental versionado. Sustituir crea version nueva; la '
  'anterior no se borra nunca.';

CREATE OR REPLACE FUNCTION fn_documento_version() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.version IS NULL OR NEW.version = 0 THEN
    SELECT COALESCE(max(version), 0) + 1 INTO NEW.version
      FROM autorizacion_documento
     WHERE id_autorizacion = NEW.id_autorizacion;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_documento_version ON autorizacion_documento;
CREATE TRIGGER tg_documento_version
BEFORE INSERT ON autorizacion_documento
FOR EACH ROW EXECUTE FUNCTION fn_documento_version();

-- Un soporte no se borra ni se reescribe: se versiona.
CREATE OR REPLACE FUNCTION fn_documento_inmutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION
    'El soporte documental no se modifica ni se borra. Suba una version nueva.'
    USING ERRCODE = 'check_violation';
END;
$$;

DROP TRIGGER IF EXISTS tg_documento_inmutable ON autorizacion_documento;
CREATE TRIGGER tg_documento_inmutable
BEFORE UPDATE OR DELETE ON autorizacion_documento
FOR EACH ROW EXECUTE FUNCTION fn_documento_inmutable();


-- ─── US-028/029 · Las excepciones ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS excepcion (
    id_excepcion      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo            VARCHAR(30) NOT NULL UNIQUE,

    --: El intento se conserva entero: si se aprueba, se ejecuta EXACTAMENTE
    --: lo que se pidió, no lo que alguien recuerde que se pidió.
    id_frasco         VARCHAR(40) NOT NULL REFERENCES frasco(id_frasco),
    id_investigador   INTEGER NOT NULL REFERENCES investigador(id_investigador),
    cantidad_g        NUMERIC(14,4) NOT NULL CHECK (cantidad_g > 0),
    cantidad_registrada NUMERIC(14,4),
    unidad_registrada VARCHAR(4),
    curso             VARCHAR(120),
    usuario_final     VARCHAR(160),

    regla_infringida  VARCHAR(40) NOT NULL,
    motivo            TEXT NOT NULL CHECK (length(btrim(motivo)) > 0),

    estado            VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
                        CHECK (estado IN ('PENDIENTE','APROBADA','RECHAZADA',
                                          'EJECUTADA','CADUCADA')),

    solicitado_por    INTEGER NOT NULL REFERENCES usuario(id_usuario),
    solicitado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    resuelto_por      INTEGER REFERENCES usuario(id_usuario),
    resuelto_en       TIMESTAMPTZ,
    comentario        TEXT,

    --: Se llena al ejecutar. Es lo que garantiza que una excepción aprobada
    --: se consume UNA sola vez: la unicidad la impone la base, no el código.
    id_movimiento     INTEGER UNIQUE REFERENCES kardex(id_movimiento),

    CONSTRAINT ck_excepcion_rechazo
      CHECK (estado <> 'RECHAZADA'
             OR (comentario IS NOT NULL AND length(btrim(comentario)) > 0)),
    CONSTRAINT ck_excepcion_resuelta
      CHECK (estado IN ('PENDIENTE','CADUCADA')
             OR (resuelto_por IS NOT NULL AND resuelto_en IS NOT NULL)),
    CONSTRAINT ck_excepcion_ejecutada
      CHECK (estado <> 'EJECUTADA' OR id_movimiento IS NOT NULL)
);

COMMENT ON TABLE excepcion IS
  'US-028/029. Un intento de consumo que la regla rechazó, conservado entero '
  'a la espera de decision. No mueve stock ni saldo hasta ejecutarse.';

CREATE INDEX IF NOT EXISTS ix_excepcion_pendientes
  ON excepcion (estado, solicitado_en) WHERE estado = 'PENDIENTE';


-- ─── US-025 · El saldo autorizado, reproducible desde las operaciones ──────
-- Saldo = autorizado − consumos confirmados + reversas.
-- No se guarda en ninguna columna a propósito: un saldo almacenado se queda
-- rancio en cuanto alguien registra un movimiento por otra vía, y aquí hay
-- varias vías (API, cargador del censo, corrección por SQL).

CREATE OR REPLACE VIEW v_autorizacion_saldo AS
SELECT
    a.id_autorizacion, a.codigo,
    a.id_investigador, inv.nombre AS titular,
    a.id_insumo, i.nombre_comercial,
    a.id_presentacion,
    a.id_establecimiento, a.id_laboratorio, lab.nombre AS laboratorio,
    a.cantidad_autorizada_g,
    a.cantidad_registrada, a.unidad_registrada,
    a.vigencia_desde, a.vigencia_hasta,
    a.estado AS estado_registro,
    a.motivo_revocacion, a.observaciones,
    COALESCE(mov.consumido_g, 0) AS consumido_g,
    a.cantidad_autorizada_g - COALESCE(mov.consumido_g, 0) AS disponible_g,
    round((a.cantidad_autorizada_g - COALESCE(mov.consumido_g, 0)) / 1000.0, 4)
      AS disponible_kg,
    doc.versiones AS documentos,
    -- El estado que se enseña combina el registro con el reloj y el consumo.
    CASE
      WHEN a.estado = 'BORRADOR'                              THEN 'BORRADOR'
      WHEN a.estado = 'REVOCADA'                              THEN 'REVOCADA'
      WHEN a.vigencia_hasta IS NOT NULL
           AND a.vigencia_hasta < CURRENT_DATE                THEN 'VENCIDA'
      WHEN a.vigencia_desde > CURRENT_DATE                    THEN 'FUTURA'
      WHEN COALESCE(mov.consumido_g, 0) >= a.cantidad_autorizada_g
                                                              THEN 'AGOTADA'
      WHEN a.vigencia_hasta IS NOT NULL
           AND a.vigencia_hasta < CURRENT_DATE + 30           THEN 'POR_VENCER'
      ELSE 'VIGENTE'
    END AS estado_efectivo
  FROM autorizacion a
  JOIN investigador inv ON inv.id_investigador = a.id_investigador
  JOIN insumo i         ON i.id_insumo = a.id_insumo
  LEFT JOIN laboratorio lab ON lab.id_laboratorio = a.id_laboratorio
  LEFT JOIN LATERAL (
        -- Solo cuenta lo que salió DE ESE titular, DE ESE insumo y DENTRO de
        -- la vigencia. Las reversas (motivo correccion, ENTRADA) devuelven
        -- saldo, que es justo lo que una corrección debe hacer.
        SELECT sum(CASE WHEN k.tipo_movimiento = 'SALIDA' THEN k.cantidad_g
                        WHEN k.tipo_movimiento = 'ENTRADA'
                             AND k.motivo = 'correccion' THEN -k.cantidad_g
                        ELSE 0 END) AS consumido_g
          FROM kardex k
          JOIN frasco f       ON f.id_frasco = k.id_frasco
          JOIN lote l         ON l.id_lote = f.id_lote
          JOIN presentacion p ON p.id_presentacion = l.id_presentacion
         WHERE p.id_insumo = a.id_insumo
           AND (a.id_presentacion IS NULL
                OR p.id_presentacion = a.id_presentacion)
           AND k.id_investigador_origen = a.id_investigador
           AND k.motivo IN ('consumo_laboratorio','entrega_directa','merma',
                            'correccion')
           AND k.fecha_operacion >= a.vigencia_desde
           AND (a.vigencia_hasta IS NULL
                OR k.fecha_operacion <= a.vigencia_hasta)
  ) mov ON TRUE
  LEFT JOIN LATERAL (
        SELECT count(*) AS versiones FROM autorizacion_documento d
         WHERE d.id_autorizacion = a.id_autorizacion
  ) doc ON TRUE;

COMMENT ON VIEW v_autorizacion_saldo IS
  'US-025/US-026. El saldo se recalcula desde el kardex en cada consulta: no '
  'hay ninguna columna de saldo que pueda quedarse rancia.';


-- ─── US-027 · La comprobación antes del consumo ────────────────────────────
-- Devuelve la autorización que ampara un consumo, o el motivo exacto por el
-- que no hay ninguna. El motivo se devuelve, no se adivina: es lo que se le
-- muestra al operario y lo que se guarda en la excepción.

CREATE OR REPLACE FUNCTION fn_autorizacion_para_consumo(
    p_id_investigador INTEGER,
    p_id_frasco       VARCHAR,
    p_cantidad_g      NUMERIC,
    p_fecha           DATE DEFAULT CURRENT_DATE
) RETURNS TABLE (
    id_autorizacion INTEGER,
    codigo          VARCHAR,
    disponible_g    NUMERIC,
    motivo_rechazo  VARCHAR
)
LANGUAGE plpgsql STABLE AS $$
DECLARE
  v_insumo VARCHAR(20);
  v_pres   VARCHAR(30);
  v_hay    BOOLEAN;
BEGIN
  SELECT p.id_insumo, p.id_presentacion INTO v_insumo, v_pres
    FROM frasco f
    JOIN lote l         ON l.id_lote = f.id_lote
    JOIN presentacion p ON p.id_presentacion = l.id_presentacion
   WHERE f.id_frasco = p_id_frasco;

  -- La que ampara: vigente, del titular, del insumo, y con saldo suficiente.
  -- Se elige la que vence antes, para gastar primero lo que caduca.
  RETURN QUERY
    SELECT s.id_autorizacion, s.codigo, s.disponible_g, NULL::VARCHAR
      FROM v_autorizacion_saldo s
     WHERE s.id_investigador = p_id_investigador
       AND s.id_insumo = v_insumo
       AND (s.id_presentacion IS NULL OR s.id_presentacion = v_pres)
       AND s.estado_registro = 'VIGENTE'
       AND s.vigencia_desde <= p_fecha
       AND (s.vigencia_hasta IS NULL OR s.vigencia_hasta >= p_fecha)
       AND s.disponible_g >= p_cantidad_g
     ORDER BY s.vigencia_hasta NULLS LAST, s.id_autorizacion
     LIMIT 1;
  IF FOUND THEN RETURN; END IF;

  -- No hay ninguna que ampare. Distinguir POR QUÉ es lo que permite escribir
  -- un mensaje útil en vez de «no autorizado».
  SELECT EXISTS (
    SELECT 1 FROM v_autorizacion_saldo s
     WHERE s.id_investigador = p_id_investigador
       AND s.id_insumo = v_insumo
       AND (s.id_presentacion IS NULL OR s.id_presentacion = v_pres)
  ) INTO v_hay;

  IF NOT v_hay THEN
    RETURN QUERY SELECT NULL::INTEGER, NULL::VARCHAR, NULL::NUMERIC,
                        'SIN_AUTORIZACION'::VARCHAR;
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1 FROM v_autorizacion_saldo s
     WHERE s.id_investigador = p_id_investigador
       AND s.id_insumo = v_insumo
       AND (s.id_presentacion IS NULL OR s.id_presentacion = v_pres)
       AND s.estado_registro = 'VIGENTE'
       AND s.vigencia_desde <= p_fecha
       AND (s.vigencia_hasta IS NULL OR s.vigencia_hasta >= p_fecha)
  ) THEN
    RETURN QUERY
      SELECT NULL::INTEGER, NULL::VARCHAR,
             max(s.disponible_g), 'SALDO_AUTORIZADO_INSUFICIENTE'::VARCHAR
        FROM v_autorizacion_saldo s
       WHERE s.id_investigador = p_id_investigador
         AND s.id_insumo = v_insumo
         AND (s.id_presentacion IS NULL OR s.id_presentacion = v_pres)
         AND s.estado_registro = 'VIGENTE';
    RETURN;
  END IF;

  RETURN QUERY SELECT NULL::INTEGER, NULL::VARCHAR, NULL::NUMERIC,
                      'AUTORIZACION_NO_VIGENTE'::VARCHAR;
END;
$$;


-- ─── El interruptor de la política ─────────────────────────────────────────
-- Exigir autorización es una DECISIÓN del establecimiento, no una constante
-- del programa. Nace apagado a propósito: encenderlo hoy, con cero
-- autorizaciones cargadas, dejaría el laboratorio sin poder registrar nada, y
-- un control que obliga a saltárselo el primer día no es un control.
-- Se enciende cuando las autorizaciones estén cargadas.

ALTER TABLE establecimiento
    ADD COLUMN IF NOT EXISTS exige_autorizacion BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN establecimiento.exige_autorizacion IS
  'US-027. Cuando es TRUE, un consumo sin autorizacion vigente y con saldo se '
  'bloquea y solo puede seguir por la via de excepcion (US-028).';


INSERT INTO schema_migration (version, descripcion)
VALUES ('010', 'Epica E4: autorizaciones de uso, soporte documental versionado '
               'y excepciones con aprobacion trazable')
ON CONFLICT (version) DO NOTHING;

COMMIT;
